### ISSUE TITLE
Decimal note lengths

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda-core#16]
Moved from https://github.com/alda-lang/alda/issues/193.

@elyisgreat had the idea of non-integer note lengths like `c0.5` (i.e. twice as long as a whole note `c1`).

A related discussion that came up in the original issue was the confusion inherent with `set-duration`, which takes a number of beats as its argument instead of a "duration" like `4` for a quarter note. To set the duration to a quarter note, you have to do `(set-duration 1)` for 1 beat. Because this is confusing, maybe we should add a `set-note-length` function that takes a note-length (e.g. `4` for a quarter note) as an argument.

**Comment by elydpg** [comment]
What if a colon were used for fractional note lengths? It makes sense for ratios and wouldn't conflict with the colon's use in declaring instruments since there would have to be a valid notelength on both sides. cX:Y would represent a Y/X c note (a note with `set-duration (4Y)/X`). So for example c2:3 would be 1.5 bars long, c8:3 would be a dotted quarter note, and c1:7 would be 7 bars long. 

Decimals could be incorporated normally and I don't think there would be a syntax conflict between the period as a "dotted note" marker and also as a decimal point. I would imagine that mixing and matching could also work, so c1.5..:1. would be a valid note length (which works out to being 9/7 bars long). One potential issue is ties; would c3:2~4 be 11/12 bars long or 3/12 bars long? Personally I think 11/12 makes more sense, but a syntax rule would have to be agreed upon.

**Comment by daveyarwood** [comment]
That's an interesting thought, but I would like to avoid adding extra syntax if we can help it. Keeping syntax simple is a major design goal of mine.

I do want to proceed with adding decimal note lengths, but for the other features you're describing here, I'd rather see how we can implement them via inline Clojure functions.

**Comment by daveyarwood** [comment]
Closed by https://github.com/alda-lang/alda-core/pull/50, available in Alda 1.0.0-rc67.
