### ISSUE TITLE
So, I don't know how to write music and then use alda.

### ISSUE THREAD

**Issue by ghost** [alda-lang/alda-core#26]
Could you tell me some learning materials about music that will help use alda?

I am new for develop the music.

**Comment by elydpg** [comment]
I would definitely check out [this article](http://blog.djy.io/alda-a-manifesto-and-gentle-introduction/) for an introduction to the language. It's quite old, but it should give you a general idea. There's also the [language documentation](https://github.com/alda-lang/alda/tree/master/doc) on the main GitHub page.

**Comment by ghost** [comment]
@elyisgreat Sorry, maybe I didn't declare the problem clearly.
I don't have music knowledge, where I could learn that? did that will help use alda?

**Comment by ghost** [comment]
Well, after I look what was I wrote, its more like I ask how to write music in alda and not how to write music for alda.
Does my English got problem? Probably.
ahhhhhh! Well, keep learning from surrounding :D

**Comment by elydpg** [comment]
Oh; you want to learn the music theory bit so that you can write music *in* alda? That's a much more vague question. There's lots of resources online to help you. Would definitely recommend checking out [r/musictheory](https://www.reddit.com/r/musictheory/) for music theory tips, then visiting the [alda slack group](http://alda-lang.slack.com) to discuss the language itself.

**Comment by daveyarwood** [comment]
@mindcat -- I think https://en.wikibooks.org/wiki/Music_Theory is a good resource for music theory for beginners. It might be a fun exercise to learn how the sheet music examples translate into Alda syntax.

I'll close this issue for now since we've linked to a couple of resources, but we can talk further on Slack if you'd like!

**Comment by ghost** [comment]
oh yes yes. music theory.
