### ISSUE TITLE
Idea: sequencer syntax

### ISSUE THREAD

**Issue by drummyfish** [alda-lang/alda-core#47]
The current syntax is based on sheet music notation, specifically the note durations are expressed as fractions, which can be hard-to read for people not used to sheet music, which is a lot of people. Take this CRAM example:

    {c2 d1 e2}1

It translates to a bar of 4 beats: 1 beat C note, 2 beats D note and 1 beat E note. This is not very readable though. My suggestion is to add this syntax:

    [c dd e]1

Which would mean the same thing. I don't have this planned exactly, but my initial ideas are:

- Stuff between [ and ] is the "sequencer" syntax.
- Notes in this syntax don't have the number durations (e.g. c2) - instead their length is decided as the relative length of the sequence of same notes to the length of the whole sequence inside the brackets.
- In the example the same notes (`dd`) are implicitly joined together. In order to play same notes NOT joined into one note, we could do one of the following:
  - There would be a separator character which would prevent the notes from being joined, for example `[c d'd e]1` or `[c d d e]` (space as separator).
  - Notes would implicitly not be joined. Instead a "continuation" character would be used, for example `[c d- e]1` (or to make it more clear: `[c- d--- e-]1`).

EDIT: [ ] symbols are apparently already used (sorry I'm new here :) ), so different ones would have to be chosen.

**Comment by elydpg** [comment]
The `[]` syntax is already used for event sequences, however adjacent notes having double the length is interesting. Definitely would have to be fleshed out though.

**Comment by jgkamat** [comment]
I'm not sure if this has been discussed before, but I would find it useful to reverse the notes lengths (as a non-music person). Maybe something like:

```
(note-reverse t)
c1 d2 c1 
```
would be something similar to what you're thinking, where '1' would be a quarter, and '2' would be a half, '4' would be a full, '8' would be a double, and so on (these are the right music words right?).

Maybe we could even set the base length, something like:
```
(note-reverse 4)
```
to make a '1' a quarter note

**Comment by elydpg** [comment]
Imo that it would be too breaking; perhaps a suffix such as `c2t` to indicate a c note which is 2 "tempos" (beats) long, and then having an attribute such as `time-signature` or `beat-length` to adjust it.

**Comment by drummyfish** [comment]
@jgkamat 

> I'm not sure if this has been discussed before, but I would find it useful to reverse the notes lengths (as a non-music person).

I've been also considering this, but I think it could be confusing when the number would sometimes be reversed and sometimes not. Plus appending special characters to notes, even very few, is what makes the classic syntax hard to read. That's why I didn't suggest this.

**Comment by jgkamat** [comment]
Also, RE: `[]` being used. I think all the parens are used, and this seems a little specific for taking some parens :). Maybe a macro/clj function could be added to flip the note lengths:

```
(reverse-length 4
piano: c1 c2 c3
)
```

This would make it clear that the notes are reversed (they are inside a function call) and it wouldn't take any parens. I'm not sure how feasable it would be though.... 😄

**Comment by daveyarwood** [comment]
I definitely would like to keep the "official" syntax predictable, i.e. what we have now, which lines up neatly with Western music theory. As @drummyfish just mentioned, it would be potentially confusing if some bit of Alda syntax meant one thing in one context and one in another.

With that in mind, I think this is a good use case for a [plugin](https://github.com/alda-lang/alda-core/issues/2).

My latest thinking on plugins is that we could provide some sort of system where a plugin writer can redefine certain functions in the alda Clojure API that is used to build scores (a.k.a. [alda.lisp](https://github.com/alda-lang/alda/blob/master/doc/alda-lisp.md)).

In this case, it would be useful if we made it so that someone could write a "reverse note lengths" plugin that would redefine the `note-length` function in such a way that the number is interpreted as a number of beats.

Then when a score starts with a line like `plugin daveyarwood/reverse-note-lengths:0.1.0` at the top, if the user has that plugin installed, the `note-length` function would work in a different way.

I haven't fully thought through this idea... would be interested to hear people's thoughts.

**Comment by daveyarwood** [comment]
Closing this issue as it is not something I'm interested in adding to Alda itself; however, I do think it would be great if we made it possible to write something like this as an Alda plugin.
