### ISSUE TITLE
Out of sync playback while using alda.now

### ISSUE THREAD

**Issue by abhi18av** [alda-lang/alda-core#67]
Hi @alda-lang/collaborators  ,

I was trying to use `alda.now` inside a `clojure` program. However, the is noticeable difference in the sound quality and playback in the way the following plays 

```clojure
(ns musicxml.scratch
  (:require [alda.lisp :refer :all]
            [alda.now  :refer :all]))


(with-new-score
  (play!
   (part "piano"
         (note (pitch :c))

         (do (volume 50) (octave 6))

         (chord (note (pitch :c))
                (note (pitch :e))
                (note (pitch :g)))

         (for [letter [:c :d :e :f :g]]
           (note (pitch letter)
                 (duration (note-length 8)))))))

```

Sometimes, it plays fine and at other times it starts by playing a sound that was supposed to be from last iteration.

Also, the speed changes as well. 

I tried doing `alda up` in the background to minimize the time needed to play the notes for the first time but it doesn't seem to make any difference here right ?

**Comment by daveyarwood** [comment]
Hi @abhi18av ,

I don't have time to dig in fully at the moment, but I do see a couple of things that I can clear up:

1. When you use Alda in a Clojure program, your Clojure process effectively becomes the Alda server -- your program is using Alda as a library to build a score and play it. Having an Alda server running in the background (via `alda up`) should make no difference.

2. The `(do (volume 50) (octave 6))` part will result in only the octave change being applied, since the octave change is the return value of the `(do ...)` form. To have both attribute changes, you can write `(volume 50) (octave 6)`

What `alda/core` and `alda/sound-engine-clj` versions are you using in your project.clj / build.boot / deps.edn?

**Comment by abhi18av** [comment]
Thanks for the quick response @daveyarwood 

I'm using the following in my `project.clj` 

```clojure
                 ;; Alda libraries
                 [alda/core             "0.3.10"]
                 [alda/sound-engine-clj "1.0.0"]

```

**Comment by abhi18av** [comment]
@daveyarwood , I was wondering that since we already an `alda` server mechanism why not also use the same with the `alda.now` process. Atleast there should be an option to be able to connect to a running server?

Also, this could effectively allow us to have the client running locally and to be able to connect to it as a remote server. Please correct me if I'm wrong here :)

**Comment by daveyarwood** [comment]
@abhi18av If I'm understanding you right, I think you're almost describing something that I have planned for Alda 2.0! :slightly_smiling_face: 

I'm planning to write a new Clojure library for live-coding Alda in Clojure. It will have a similar API to `alda.now` / `alda.lisp`, but instead of creating and playing the score in your Clojure program, it will generate Alda code and shell out to `alda` to play the generated score.

You could think of this as the Clojure program being an alternative Alda client, and the playback of the score will still be done by the Alda server that you have running. I think this is probably a better approach than the `alda.now` library we have now, because in my experience, there seem to be some performance issues related to using the same Clojure process (e.g. a REPL using the Alda libraries) to play scores one after another.

The client/server/workers architecture that we use when you play scores via the `alda` CLI solves this problem in that there is a separate worker process for each score being played. So, I think a better approach would be to leverage that by writing Clojure programs that interact with the server instead.

I'm rambling a bit, but hopefully this makes sense!

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-sound-engine-clj/issues/15

**Comment by abhi18av** [comment]
Hi @daveyarwood , 

Apologies for not replying earlier - life in a startup is crazy fast hehe 

I am happy to know that you have already thought about this issue in the roadmap for `alda v2.0` and I am looking forward to be able to connect to an `alda server` using my clojure programs.

Also, when you come to think about it, it would be much easier to have `ClojureScript` running in the browser and communicating with a remote `alda server` and thus enabling us to offer `alda server as a service`.

Are you working on a public roadmap for `alda` using the Github `projects` feature?

**Comment by daveyarwood** [comment]
The closest thing we have to a roadmap is our [waffle.io board](https://waffle.io/alda-lang/alda), which is a view of GitHub issues across all of the repos in the alda-lang org. Basically, anything in the "Up for Grabs" column is ready to be worked on by anyone, including me.

Alda 2.0 is still in the planning stages, so I'm hesitant to add any of that work to the board yet while I'm figuring things out and experimenting, but at some point when I've picked up momentum on that, I will start to create issues and they'll show up on the board.
