### ISSUE TITLE
Command not found - El Capitan, Mac OS

### ISSUE THREAD

**Issue by sbandx** [alda-lang/alda-core#70]
I have Java 8 installed, and get  command not found error when trying to update or use alda up

**Comment by TBuc** [comment]
Hi @sbandx, seems alda is not in your path.

Could you try changing your terminal's directory to the one where alda is located before issuing the `alda up` command and let me know?

In case it still doesn't work, a screenshot of your terminal where the command fails could help assisting you.

**Comment by sbandx** [comment]
I am changing to the directory where 'alda' is located and am using the latest available version:


ElCapitan:Applications serge$ pwd
/Users/serge/Applications
ElCapitan:Applications serge$ ls
Audacity			alda
BlueJ				alda-master
Cassio				javaforosx.dmg
Certificates			jre-8u201-macosx-x64.dmg
Chrome Apps.localized		jre-8u201-macosx-x64.tar.gz
ClamXAV.app			swell-foop
POVray				swell-foop-js
ElCapitan:Applications serge$ alda up
-bash: alda: command not found
ElCapitan:Applications serge$

**Comment by sbandx** [comment]
alda has execute permissions: 
-rwxr-xr-x@  1 serge  staff   7149618 Mar 26 07:42 alda

**Comment by TBuc** [comment]
I don't recall if MacOS requires `./` prefix in order to execute binaries.
To clear any doubt, could you try issuing `./alda` in place of `alda` in your terminal and let me know the outcome?

**Comment by daveyarwood** [comment]
If you are in the directory where `alda` is located, you can run it with `./alda` (meaning "run the program in this directory called `alda`")

It is more convenient to put `alda` on your PATH so that it can be run (as `alda`, not `./alda`) from any directory.

To see your PATH, run `echo $PATH`. You can put `alda` in any of those directories. I think `/usr/local/bin` is typically included in the PATH on MacOS, but I'm not 100% sure.

**Comment by sbandx** [comment]
That was it.. ./alda

thank you
