### ISSUE TITLE
Global Attributes should only be settable on their own dedicated lines

### ISSUE THREAD

**Issue by elydpg** [alda-lang/alda-core#89]
It seems that, as per the resolution of #24, @daveyarwood has elected not to change the behaviour of global attributes such that when they are called they are put into effect from that point forward *in the score*, not necessarily that point forward *in time*. As such, it would be clearer if there was a syntax error or at least a warning when changing a global attribute interspersed with another event. In other words,

```
trumpet: c8 c c c c c c c c 
trombone: c8 c c c (tempo! 250) c c c c c
```

Should cause a syntax error, though

```
trumpet: c8 c c c c c c c c 
trombone: c8 c c c
(tempo! 250)
trombone: c c c c c
```

Would retain the same behaviour, which is currently identical to the above segment.

**Comment by daveyarwood** [comment]
I don't think it would be helpful if we threw a syntax error in this situation. I think the first example (where `(tempo! 250)` is written in the same line as the rest of the trombone part) actually makes it clearer where the global tempo change falls. In the second example, it isn't immediately clear that the global tempo change is happening within the context of the trombone part. It looks more like a "global event" that is separate from any particular part, which is misleading because it really is being placed within the context of the trombone part.
